accelerate launch --main_process_port 6777 \
    --config_file ./configs/config.yaml \
    valley/train/train_accelerate.py \
    --model_name_or_path ../checkpoints/pretrain-stable-valley-13b-v3 \
    --data_path ../meta_data/finetune_data/LLaVA-Instruct-150K/llava_instruct_150k.json \
    --video_data_path ../meta_data/finetune_data/Valley-Instruct/valley_videochat_instruct_52k.json \
    --image_folder ../meta_data/finetune_data/train2014 \
    --video_folder ../meta_data/finetune_data/Valley-Instruct/videos \
    --tune_mm_mlp_adapter True \
    --vision_tower openai/clip-vit-large-patch14 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 False \
    --fp16 True \
    --output_dir ../checkpoints/zeros3-stable-valley-13b-v3 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy no \
    --save_strategy steps \
    --save_steps 3000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb \
    --fast_epoch False 